---
swagger: "2.0"
info:
  version: 1.0.0
  title: Greeting Server
paths:
  /hello:
    get:
      produces:
        - text/plain
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to World if not given
      operationId: getGreeting
      responses:
        200:
          description: returns a greeting
          schema:
            type: string
            description: contains the actual greeting as plain text
    post:
      consumes:
        - application/json
      produces:
        - text/plain
      parameters:
        - in: body
          name: greeting
          description: Greeting object
          required: true
          schema:
            $ref: "#/definitions/Greeting"
      operationId: postGreeting
      responses:
        200:
          description: returns a custom greeting
          schema:
            $ref: "#/definitions/GreatingResponse"
definitions:
  Greeting:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  GreatingResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
